Vet clinic database: query and update animals table
MesakDuduCoder/Vet-clinic-database pull request #2
Opened 2023-07-18 17:17 UTC by MesakDuduCoder

1. I added a column species of type string to my animals table.
2. I inserted more animals to my animals table.
3. Inside a transaction I updated the animals table by setting the species column to unspecified. Verify that change was made. Then roll back the change and verify that the species columns went back to the state before the transaction.
4. Inside a transaction:
    I updated the animals table by setting the species column to digimon for all animals that have a name ending in 
    mon.
    I updated the animals table by setting the species column to pokemon for all animals that don't have species already 
    set.
    I verify that changes were made.
    I commited the transaction.
    I verified that changes persist after commit.

![1](https://github.com/MesakDuduCoder/Vet-clinic-database/assets/99257836/86ddd273-a2c0-483d-a19a-f89daba21527)

5. Inside a transaction I deleted all records in the animals table, then rolled back the transaction. After the rollback I verify all records in the animals table still exists.

![2](https://github.com/MesakDuduCoder/Vet-clinic-database/assets/99257836/1eec5a96-38d6-4a64-aa34-62b80914a1db)

6. Inside a transaction:
    I deleted all animals born after Jan 1st, 2022.
    I created a savepoint for the transaction.
    I updated all animals' weight to be their weight multiplied by -1.
    I rollback to the savepoint
    I updated all animals' weights that are negative to be their weight multiplied by -1.
    I commited transaction

![3](https://github.com/MesakDuduCoder/Vet-clinic-database/assets/99257836/66becf15-2210-4a8d-b1a8-806a26946859)

7. I wrote queries to answer the following questions:
    How many animals are there?
    How many animals have never tried to escape?
    What is the average weight of animals?
    Who escapes the most, neutered or not neutered animals?
    What is the minimum and maximum weight of each type of animal?
    What is the average number of escape attempts per animal type of those born between 1990 and 2000?

![4](https://github.com/MesakDuduCoder/Vet-clinic-database/assets/99257836/722b4506-311d-4757-9d7b-c5fa8c7ce290)

![5](https://github.com/MesakDuduCoder/Vet-clinic-database/assets/99257836/b41c7602-081b-43c0-9244-58efe9286acc)

2023-07-18 19:12 UTC, Lizdev-05 requested changes
Hi @MesakDuduCoder , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/YYht2UTV41u1vxHTss/giphy-downsized-medium.gif"/>

## Highlights
:heavy_check_mark: Professional Readme file :+1: 
:heavy_check_mark: Good commit history :+1:
:heavy_check_mark: No linter error :+1: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-18 19:12 UTC, Lizdev-05 commented on schema.sql
>  );
- [ ] You should not add the species column by editing command for the created animal table :relaxed:  Please I suggest that add the species the `ALTER` SQL command to add the column because that animal table is already :pray:

2023-07-18 19:12 UTC, Lizdev-05 commented on queries.sql
> +
- [ ] Please you are missing this requirement so make sure that you complete this :point_down: 
  
  - Inside a transaction:
  
    * `UPDATE` the animals table by setting the species column to unspecified, then roll back the change (\*\*for this step students are explicitly asked to verify that change was made and rollbacked, so make sure that they included all steps as in the example below \*\*).

2023-07-19 03:11 UTC, IngDavidTM approved these changes
Hi @MesakDuduCoder  🙋‍♂️, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations!  🎉💯🌟 

## Top highlight 🎯

- The Pull Request follows the GitFlow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 
<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-19 04:11 UTC, merged